/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AdapterStatusList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdapterStatusList{}

// AdapterStatusList struct for AdapterStatusList
type AdapterStatusList struct {
	Items []AdapterStatus `json:"items"`
	Kind  string          `json:"kind"`
	Page  int32           `json:"page"`
	Size  int32           `json:"size"`
	Total int32           `json:"total"`
}

type _AdapterStatusList AdapterStatusList

// NewAdapterStatusList instantiates a new AdapterStatusList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdapterStatusList(items []AdapterStatus, kind string, page int32, size int32, total int32) *AdapterStatusList {
	this := AdapterStatusList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewAdapterStatusListWithDefaults instantiates a new AdapterStatusList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdapterStatusListWithDefaults() *AdapterStatusList {
	this := AdapterStatusList{}
	return &this
}

// GetItems returns the Items field value
func (o *AdapterStatusList) GetItems() []AdapterStatus {
	if o == nil {
		var ret []AdapterStatus
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusList) GetItemsOk() ([]AdapterStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AdapterStatusList) SetItems(v []AdapterStatus) {
	o.Items = v
}

// GetKind returns the Kind field value
func (o *AdapterStatusList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AdapterStatusList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *AdapterStatusList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *AdapterStatusList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *AdapterStatusList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *AdapterStatusList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *AdapterStatusList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AdapterStatusList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AdapterStatusList) SetTotal(v int32) {
	o.Total = v
}

func (o AdapterStatusList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdapterStatusList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *AdapterStatusList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"kind",
		"page",
		"size",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdapterStatusList := _AdapterStatusList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdapterStatusList)

	if err != nil {
		return err
	}

	*o = AdapterStatusList(varAdapterStatusList)

	return err
}

type NullableAdapterStatusList struct {
	value *AdapterStatusList
	isSet bool
}

func (v NullableAdapterStatusList) Get() *AdapterStatusList {
	return v.value
}

func (v *NullableAdapterStatusList) Set(val *AdapterStatusList) {
	v.value = val
	v.isSet = true
}

func (v NullableAdapterStatusList) IsSet() bool {
	return v.isSet
}

func (v *NullableAdapterStatusList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdapterStatusList(val *AdapterStatusList) *NullableAdapterStatusList {
	return &NullableAdapterStatusList{value: val, isSet: true}
}

func (v NullableAdapterStatusList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdapterStatusList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
