/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AdapterStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdapterStatus{}

// AdapterStatus struct for AdapterStatus
type AdapterStatus struct {
	// Name of the adapter that generated this status (Validator, DNS...)
	Adapter string `json:"adapter"`
	// Which generation for an entity (Clusters, NodePools) was current at the time of creating this status
	ObservedGeneration int32 `json:"observed_generation"`
	// Kubernetes-style conditions tracking adapter state
	Conditions []Condition `json:"conditions"`
	// Adapter-specific data (structure varies by adapter type)
	Data     map[string]interface{} `json:"data,omitempty"`
	Metadata *AdapterStatusMetadata `json:"metadata,omitempty"`
}

type _AdapterStatus AdapterStatus

// NewAdapterStatus instantiates a new AdapterStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdapterStatus(adapter string, observedGeneration int32, conditions []Condition) *AdapterStatus {
	this := AdapterStatus{}
	this.Adapter = adapter
	this.ObservedGeneration = observedGeneration
	this.Conditions = conditions
	return &this
}

// NewAdapterStatusWithDefaults instantiates a new AdapterStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdapterStatusWithDefaults() *AdapterStatus {
	this := AdapterStatus{}
	return &this
}

// GetAdapter returns the Adapter field value
func (o *AdapterStatus) GetAdapter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Adapter
}

// GetAdapterOk returns a tuple with the Adapter field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetAdapterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Adapter, true
}

// SetAdapter sets field value
func (o *AdapterStatus) SetAdapter(v string) {
	o.Adapter = v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *AdapterStatus) GetObservedGeneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetObservedGenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *AdapterStatus) SetObservedGeneration(v int32) {
	o.ObservedGeneration = v
}

// GetConditions returns the Conditions field value
func (o *AdapterStatus) GetConditions() []Condition {
	if o == nil {
		var ret []Condition
		return ret
	}

	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetConditionsOk() ([]Condition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conditions, true
}

// SetConditions sets field value
func (o *AdapterStatus) SetConditions(v []Condition) {
	o.Conditions = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AdapterStatus) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AdapterStatus) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *AdapterStatus) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AdapterStatus) GetMetadata() AdapterStatusMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret AdapterStatusMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdapterStatus) GetMetadataOk() (*AdapterStatusMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AdapterStatus) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given AdapterStatusMetadata and assigns it to the Metadata field.
func (o *AdapterStatus) SetMetadata(v AdapterStatusMetadata) {
	o.Metadata = &v
}

func (o AdapterStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdapterStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["adapter"] = o.Adapter
	toSerialize["observed_generation"] = o.ObservedGeneration
	toSerialize["conditions"] = o.Conditions
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *AdapterStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"adapter",
		"observed_generation",
		"conditions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdapterStatus := _AdapterStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdapterStatus)

	if err != nil {
		return err
	}

	*o = AdapterStatus(varAdapterStatus)

	return err
}

type NullableAdapterStatus struct {
	value *AdapterStatus
	isSet bool
}

func (v NullableAdapterStatus) Get() *AdapterStatus {
	return v.value
}

func (v *NullableAdapterStatus) Set(val *AdapterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAdapterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAdapterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdapterStatus(val *AdapterStatus) *NullableAdapterStatus {
	return &NullableAdapterStatus{value: val, isSet: true}
}

func (v NullableAdapterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdapterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
