/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NodePoolList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodePoolList{}

// NodePoolList struct for NodePoolList
type NodePoolList struct {
	Items []NodePool `json:"items"`
	Kind  string     `json:"kind"`
	Page  int32      `json:"page"`
	Size  int32      `json:"size"`
	Total int32      `json:"total"`
}

type _NodePoolList NodePoolList

// NewNodePoolList instantiates a new NodePoolList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodePoolList(items []NodePool, kind string, page int32, size int32, total int32) *NodePoolList {
	this := NodePoolList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewNodePoolListWithDefaults instantiates a new NodePoolList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodePoolListWithDefaults() *NodePoolList {
	this := NodePoolList{}
	return &this
}

// GetItems returns the Items field value
func (o *NodePoolList) GetItems() []NodePool {
	if o == nil {
		var ret []NodePool
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *NodePoolList) GetItemsOk() ([]NodePool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *NodePoolList) SetItems(v []NodePool) {
	o.Items = v
}

// GetKind returns the Kind field value
func (o *NodePoolList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *NodePoolList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *NodePoolList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *NodePoolList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *NodePoolList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *NodePoolList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *NodePoolList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *NodePoolList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *NodePoolList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *NodePoolList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *NodePoolList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *NodePoolList) SetTotal(v int32) {
	o.Total = v
}

func (o NodePoolList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodePoolList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *NodePoolList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"kind",
		"page",
		"size",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodePoolList := _NodePoolList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodePoolList)

	if err != nil {
		return err
	}

	*o = NodePoolList(varNodePoolList)

	return err
}

type NullableNodePoolList struct {
	value *NodePoolList
	isSet bool
}

func (v NullableNodePoolList) Get() *NodePoolList {
	return v.value
}

func (v *NullableNodePoolList) Set(val *NodePoolList) {
	v.value = val
	v.isSet = true
}

func (v NullableNodePoolList) IsSet() bool {
	return v.isSet
}

func (v *NullableNodePoolList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodePoolList(val *NodePoolList) *NullableNodePoolList {
	return &NullableNodePoolList{value: val, isSet: true}
}

func (v NullableNodePoolList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodePoolList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
