/*
HyperFleet API

HyperFleet API provides simple CRUD operations for managing cluster resources and their status history.  **Architecture**: Simple CRUD only, no business logic, no event creation. Sentinel operator handles all orchestration logic. Adapters handle the specifics of managing spec

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ClusterBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterBase{}

// ClusterBase struct for ClusterBase
type ClusterBase struct {
	Kind string `json:"kind"`
	// Cluster name (unique)
	Name string `json:"name" validate:"regexp=^[a-z0-9-]+$"`
	// Cluster specification CLM doesn't know how to unmarshall the spec, it only stores and forwards to adapters to do their job But CLM will validate the schema before accepting the request
	Spec map[string]interface{} `json:"spec"`
	// labels for the API resource as pairs of name:value strings
	Labels *map[string]string `json:"labels,omitempty"`
	// Resource identifier
	Id *string `json:"id,omitempty"`
	// Resource URI
	Href *string `json:"href,omitempty"`
}

type _ClusterBase ClusterBase

// NewClusterBase instantiates a new ClusterBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterBase(kind string, name string, spec map[string]interface{}) *ClusterBase {
	this := ClusterBase{}
	this.Kind = kind
	return &this
}

// NewClusterBaseWithDefaults instantiates a new ClusterBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterBaseWithDefaults() *ClusterBase {
	this := ClusterBase{}
	var kind string = "Cluster"
	this.Kind = kind
	return &this
}

// GetKind returns the Kind field value
func (o *ClusterBase) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ClusterBase) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *ClusterBase) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *ClusterBase) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterBase) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterBase) SetName(v string) {
	o.Name = v
}

// GetSpec returns the Spec field value
func (o *ClusterBase) GetSpec() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *ClusterBase) GetSpecOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Spec, true
}

// SetSpec sets field value
func (o *ClusterBase) SetSpec(v map[string]interface{}) {
	o.Spec = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ClusterBase) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterBase) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ClusterBase) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ClusterBase) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClusterBase) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterBase) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClusterBase) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClusterBase) SetId(v string) {
	o.Id = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ClusterBase) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterBase) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ClusterBase) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ClusterBase) SetHref(v string) {
	o.Href = &v
}

func (o ClusterBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	toSerialize["spec"] = o.Spec
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	return toSerialize, nil
}

func (o *ClusterBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"name",
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClusterBase := _ClusterBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClusterBase)

	if err != nil {
		return err
	}

	*o = ClusterBase(varClusterBase)

	return err
}

type NullableClusterBase struct {
	value *ClusterBase
	isSet bool
}

func (v NullableClusterBase) Get() *ClusterBase {
	return v.value
}

func (v *NullableClusterBase) Set(val *ClusterBase) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterBase) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterBase(val *ClusterBase) *NullableClusterBase {
	return &NullableClusterBase{value: val, isSet: true}
}

func (v NullableClusterBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
