apiVersion: v2
name: hyperfleet-api
description: HyperFleet API - Cluster Lifecycle Management Service
type: application
version: 1.0.0
appVersion: "0.0.0-dev"
maintainers:
  - name: HyperFleet Team
    email: hyperfleet-team@redhat.com
keywords:
  - hyperfleet
  - api
  - kubernetes
  - cluster-management
home: https://github.com/openshift-hyperfleet/hyperfleet-api
