// Code generated by MockGen. DO NOT EDIT.
// Source: adapter_status.go
//
// Generated by this command:
//
//	mockgen -source=adapter_status.go -package=services -destination=adapter_status_mock.go
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	api "github.com/openshift-hyperfleet/hyperfleet-api/pkg/api"
	errors "github.com/openshift-hyperfleet/hyperfleet-api/pkg/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapterStatusService is a mock of AdapterStatusService interface.
type MockAdapterStatusService struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterStatusServiceMockRecorder
	isgomock struct{}
}

// MockAdapterStatusServiceMockRecorder is the mock recorder for MockAdapterStatusService.
type MockAdapterStatusServiceMockRecorder struct {
	mock *MockAdapterStatusService
}

// NewMockAdapterStatusService creates a new mock instance.
func NewMockAdapterStatusService(ctrl *gomock.Controller) *MockAdapterStatusService {
	mock := &MockAdapterStatusService{ctrl: ctrl}
	mock.recorder = &MockAdapterStatusServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapterStatusService) EXPECT() *MockAdapterStatusServiceMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockAdapterStatusService) All(ctx context.Context) (api.AdapterStatusList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].(api.AdapterStatusList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockAdapterStatusServiceMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockAdapterStatusService)(nil).All), ctx)
}

// Create mocks base method.
func (m *MockAdapterStatusService) Create(ctx context.Context, adapterStatus *api.AdapterStatus) (*api.AdapterStatus, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, adapterStatus)
	ret0, _ := ret[0].(*api.AdapterStatus)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdapterStatusServiceMockRecorder) Create(ctx, adapterStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdapterStatusService)(nil).Create), ctx, adapterStatus)
}

// Delete mocks base method.
func (m *MockAdapterStatusService) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdapterStatusServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdapterStatusService)(nil).Delete), ctx, id)
}

// FindByResource mocks base method.
func (m *MockAdapterStatusService) FindByResource(ctx context.Context, resourceType, resourceID string) (api.AdapterStatusList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByResource", ctx, resourceType, resourceID)
	ret0, _ := ret[0].(api.AdapterStatusList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// FindByResource indicates an expected call of FindByResource.
func (mr *MockAdapterStatusServiceMockRecorder) FindByResource(ctx, resourceType, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByResource", reflect.TypeOf((*MockAdapterStatusService)(nil).FindByResource), ctx, resourceType, resourceID)
}

// FindByResourceAndAdapter mocks base method.
func (m *MockAdapterStatusService) FindByResourceAndAdapter(ctx context.Context, resourceType, resourceID, adapter string) (*api.AdapterStatus, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByResourceAndAdapter", ctx, resourceType, resourceID, adapter)
	ret0, _ := ret[0].(*api.AdapterStatus)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// FindByResourceAndAdapter indicates an expected call of FindByResourceAndAdapter.
func (mr *MockAdapterStatusServiceMockRecorder) FindByResourceAndAdapter(ctx, resourceType, resourceID, adapter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByResourceAndAdapter", reflect.TypeOf((*MockAdapterStatusService)(nil).FindByResourceAndAdapter), ctx, resourceType, resourceID, adapter)
}

// FindByResourcePaginated mocks base method.
func (m *MockAdapterStatusService) FindByResourcePaginated(ctx context.Context, resourceType, resourceID string, listArgs *ListArguments) (api.AdapterStatusList, int64, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByResourcePaginated", ctx, resourceType, resourceID, listArgs)
	ret0, _ := ret[0].(api.AdapterStatusList)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*errors.ServiceError)
	return ret0, ret1, ret2
}

// FindByResourcePaginated indicates an expected call of FindByResourcePaginated.
func (mr *MockAdapterStatusServiceMockRecorder) FindByResourcePaginated(ctx, resourceType, resourceID, listArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByResourcePaginated", reflect.TypeOf((*MockAdapterStatusService)(nil).FindByResourcePaginated), ctx, resourceType, resourceID, listArgs)
}

// Get mocks base method.
func (m *MockAdapterStatusService) Get(ctx context.Context, id string) (*api.AdapterStatus, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*api.AdapterStatus)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdapterStatusServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdapterStatusService)(nil).Get), ctx, id)
}

// Replace mocks base method.
func (m *MockAdapterStatusService) Replace(ctx context.Context, adapterStatus *api.AdapterStatus) (*api.AdapterStatus, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, adapterStatus)
	ret0, _ := ret[0].(*api.AdapterStatus)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockAdapterStatusServiceMockRecorder) Replace(ctx, adapterStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockAdapterStatusService)(nil).Replace), ctx, adapterStatus)
}

// Upsert mocks base method.
func (m *MockAdapterStatusService) Upsert(ctx context.Context, adapterStatus *api.AdapterStatus) (*api.AdapterStatus, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, adapterStatus)
	ret0, _ := ret[0].(*api.AdapterStatus)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAdapterStatusServiceMockRecorder) Upsert(ctx, adapterStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAdapterStatusService)(nil).Upsert), ctx, adapterStatus)
}
