// Code generated by MockGen. DO NOT EDIT.
// Source: cluster.go
//
// Generated by this command:
//
//	mockgen -source=cluster.go -package=services -destination=cluster_mock.go
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	api "github.com/openshift-hyperfleet/hyperfleet-api/pkg/api"
	errors "github.com/openshift-hyperfleet/hyperfleet-api/pkg/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockClusterService is a mock of ClusterService interface.
type MockClusterService struct {
	ctrl     *gomock.Controller
	recorder *MockClusterServiceMockRecorder
	isgomock struct{}
}

// MockClusterServiceMockRecorder is the mock recorder for MockClusterService.
type MockClusterServiceMockRecorder struct {
	mock *MockClusterService
}

// NewMockClusterService creates a new mock instance.
func NewMockClusterService(ctrl *gomock.Controller) *MockClusterService {
	mock := &MockClusterService{ctrl: ctrl}
	mock.recorder = &MockClusterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterService) EXPECT() *MockClusterServiceMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockClusterService) All(ctx context.Context) (api.ClusterList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].(api.ClusterList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockClusterServiceMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockClusterService)(nil).All), ctx)
}

// Create mocks base method.
func (m *MockClusterService) Create(ctx context.Context, cluster *api.Cluster) (*api.Cluster, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cluster)
	ret0, _ := ret[0].(*api.Cluster)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClusterServiceMockRecorder) Create(ctx, cluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClusterService)(nil).Create), ctx, cluster)
}

// Delete mocks base method.
func (m *MockClusterService) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterService)(nil).Delete), ctx, id)
}

// FindByIDs mocks base method.
func (m *MockClusterService) FindByIDs(ctx context.Context, ids []string) (api.ClusterList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].(api.ClusterList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockClusterServiceMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockClusterService)(nil).FindByIDs), ctx, ids)
}

// Get mocks base method.
func (m *MockClusterService) Get(ctx context.Context, id string) (*api.Cluster, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*api.Cluster)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterService)(nil).Get), ctx, id)
}

// OnDelete mocks base method.
func (m *MockClusterService) OnDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnDelete indicates an expected call of OnDelete.
func (mr *MockClusterServiceMockRecorder) OnDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDelete", reflect.TypeOf((*MockClusterService)(nil).OnDelete), ctx, id)
}

// OnUpsert mocks base method.
func (m *MockClusterService) OnUpsert(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUpsert", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnUpsert indicates an expected call of OnUpsert.
func (mr *MockClusterServiceMockRecorder) OnUpsert(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpsert", reflect.TypeOf((*MockClusterService)(nil).OnUpsert), ctx, id)
}

// Replace mocks base method.
func (m *MockClusterService) Replace(ctx context.Context, cluster *api.Cluster) (*api.Cluster, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, cluster)
	ret0, _ := ret[0].(*api.Cluster)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockClusterServiceMockRecorder) Replace(ctx, cluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockClusterService)(nil).Replace), ctx, cluster)
}

// UpdateClusterStatusFromAdapters mocks base method.
func (m *MockClusterService) UpdateClusterStatusFromAdapters(ctx context.Context, clusterID string) (*api.Cluster, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClusterStatusFromAdapters", ctx, clusterID)
	ret0, _ := ret[0].(*api.Cluster)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateClusterStatusFromAdapters indicates an expected call of UpdateClusterStatusFromAdapters.
func (mr *MockClusterServiceMockRecorder) UpdateClusterStatusFromAdapters(ctx, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClusterStatusFromAdapters", reflect.TypeOf((*MockClusterService)(nil).UpdateClusterStatusFromAdapters), ctx, clusterID)
}
