// Code generated by MockGen. DO NOT EDIT.
// Source: generic.go
//
// Generated by this command:
//
//	mockgen -source=generic.go -package=services -destination=generic_mock.go
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	api "github.com/openshift-hyperfleet/hyperfleet-api/pkg/api"
	errors "github.com/openshift-hyperfleet/hyperfleet-api/pkg/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockGenericService is a mock of GenericService interface.
type MockGenericService struct {
	ctrl     *gomock.Controller
	recorder *MockGenericServiceMockRecorder
	isgomock struct{}
}

// MockGenericServiceMockRecorder is the mock recorder for MockGenericService.
type MockGenericServiceMockRecorder struct {
	mock *MockGenericService
}

// NewMockGenericService creates a new mock instance.
func NewMockGenericService(ctrl *gomock.Controller) *MockGenericService {
	mock := &MockGenericService{ctrl: ctrl}
	mock.recorder = &MockGenericServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenericService) EXPECT() *MockGenericServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGenericService) List(ctx context.Context, username string, args *ListArguments, resourceList any) (*api.PagingMeta, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, username, args, resourceList)
	ret0, _ := ret[0].(*api.PagingMeta)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGenericServiceMockRecorder) List(ctx, username, args, resourceList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGenericService)(nil).List), ctx, username, args, resourceList)
}
