// Code generated by MockGen. DO NOT EDIT.
// Source: node_pool.go
//
// Generated by this command:
//
//	mockgen -source=node_pool.go -package=services -destination=node_pool_mock.go
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	api "github.com/openshift-hyperfleet/hyperfleet-api/pkg/api"
	errors "github.com/openshift-hyperfleet/hyperfleet-api/pkg/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockNodePoolService is a mock of NodePoolService interface.
type MockNodePoolService struct {
	ctrl     *gomock.Controller
	recorder *MockNodePoolServiceMockRecorder
	isgomock struct{}
}

// MockNodePoolServiceMockRecorder is the mock recorder for MockNodePoolService.
type MockNodePoolServiceMockRecorder struct {
	mock *MockNodePoolService
}

// NewMockNodePoolService creates a new mock instance.
func NewMockNodePoolService(ctrl *gomock.Controller) *MockNodePoolService {
	mock := &MockNodePoolService{ctrl: ctrl}
	mock.recorder = &MockNodePoolServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodePoolService) EXPECT() *MockNodePoolServiceMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockNodePoolService) All(ctx context.Context) (api.NodePoolList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].(api.NodePoolList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockNodePoolServiceMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockNodePoolService)(nil).All), ctx)
}

// Create mocks base method.
func (m *MockNodePoolService) Create(ctx context.Context, nodePool *api.NodePool) (*api.NodePool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, nodePool)
	ret0, _ := ret[0].(*api.NodePool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNodePoolServiceMockRecorder) Create(ctx, nodePool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNodePoolService)(nil).Create), ctx, nodePool)
}

// Delete mocks base method.
func (m *MockNodePoolService) Delete(ctx context.Context, id string) *errors.ServiceError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(*errors.ServiceError)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNodePoolServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNodePoolService)(nil).Delete), ctx, id)
}

// FindByIDs mocks base method.
func (m *MockNodePoolService) FindByIDs(ctx context.Context, ids []string) (api.NodePoolList, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, ids)
	ret0, _ := ret[0].(api.NodePoolList)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockNodePoolServiceMockRecorder) FindByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockNodePoolService)(nil).FindByIDs), ctx, ids)
}

// Get mocks base method.
func (m *MockNodePoolService) Get(ctx context.Context, id string) (*api.NodePool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*api.NodePool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNodePoolServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNodePoolService)(nil).Get), ctx, id)
}

// OnDelete mocks base method.
func (m *MockNodePoolService) OnDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnDelete indicates an expected call of OnDelete.
func (mr *MockNodePoolServiceMockRecorder) OnDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDelete", reflect.TypeOf((*MockNodePoolService)(nil).OnDelete), ctx, id)
}

// OnUpsert mocks base method.
func (m *MockNodePoolService) OnUpsert(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUpsert", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnUpsert indicates an expected call of OnUpsert.
func (mr *MockNodePoolServiceMockRecorder) OnUpsert(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpsert", reflect.TypeOf((*MockNodePoolService)(nil).OnUpsert), ctx, id)
}

// Replace mocks base method.
func (m *MockNodePoolService) Replace(ctx context.Context, nodePool *api.NodePool) (*api.NodePool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, nodePool)
	ret0, _ := ret[0].(*api.NodePool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockNodePoolServiceMockRecorder) Replace(ctx, nodePool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockNodePoolService)(nil).Replace), ctx, nodePool)
}

// UpdateNodePoolStatusFromAdapters mocks base method.
func (m *MockNodePoolService) UpdateNodePoolStatusFromAdapters(ctx context.Context, nodePoolID string) (*api.NodePool, *errors.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodePoolStatusFromAdapters", ctx, nodePoolID)
	ret0, _ := ret[0].(*api.NodePool)
	ret1, _ := ret[1].(*errors.ServiceError)
	return ret0, ret1
}

// UpdateNodePoolStatusFromAdapters indicates an expected call of UpdateNodePoolStatusFromAdapters.
func (mr *MockNodePoolServiceMockRecorder) UpdateNodePoolStatusFromAdapters(ctx, nodePoolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodePoolStatusFromAdapters", reflect.TypeOf((*MockNodePoolService)(nil).UpdateNodePoolStatusFromAdapters), ctx, nodePoolID)
}
